"""v3_features

Revision ID: d7a2602dcf9a
Revises: 123773ffa368
Create Date: 2026-03-21 23:44:58.457491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a2602dcf9a'
down_revision: Union[str, Sequence[str], None] = '123773ffa368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('SALE', 'RECEIPT', 'WRITE_OFF', name='transactiontype'), nullable=False, server_default='SALE'))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('order_group_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_order_group_id'), ['order_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_order_group_id'))
        batch_op.drop_column('order_group_id')
        batch_op.drop_column('reason')
        batch_op.drop_column('type')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
